displayName: Fail2Ban middleware impelementation
type: middleware

import: github.com/tommoulard/fail2ban

summary: 'Blacklist (or whitelist) IP depending on some conditions'

testData:
    Whitelist:
      Files:
        - "file1.txt"
        - "file2.txt"
      IP:
        - "::1"
        - "127.0.0.1"
    Blacklist:
      Files:
        - "file3.txt"
        - "file4.txt"
      IP:
        - "::1"
        - "127.0.0.1"
