displayName: Fail2Ban
type: middleware

import: github.com/tommoulard/fail2ban

summary: 'Blacklist (or whitelist) IP depending on some conditions'

testData:
  whitelist:
    files:
        - "file1.txt"
        - "file2.txt"
    ip:
        - "::1"
        - "127.0.0.1"
  blacklist:
    files:
        - "file3.txt"
        - "file4.txt"
    ip:
        - "::1"
        - "127.0.0.1"
  rules:
    ignorecommand: ""
    bantime: "3h"
    findtime: "10m"
    maxretry: 4
    backend: ""
    usedns: ""
    logencoding: "UTF-8"
    enabled: true
    mode: ""
    filter: ""
    destemail: ""
    sender: ""
    mta: ""
    protocol: ""
    chain: ""
    ports: "0:8000"
    fail2banAgent: ""
    banaction: ""
    banactionAllports: ""
    actionAbuseipdb: ""
    action: ""
